### ISSUE TITLE
跟踪学习中。。。

### ISSUE THREAD

**Issue by vector4wang** [CheckChe0803/flink-recommandSystem-demo#1]
最近我也在看flink，想实现一个简单的实时推荐系统，找了很久找到这了，准备在本地把楼主的项目搭建起来！！！

看好楼主,还希望能有搭建步骤~~~

**Comment by CheckChe0803** [comment]
好的,共同学习!
近期把搭建流程完善

**Comment by vector4wang** [comment]
我这一块是小白，只不过我们组要用到flink，我作为先行部队，需要弄一套简单的实时推荐系统，能跑起来运行。

目前hbase mysql 和你提到的redis我都会用docker搭建，单机的，然后再来运行你的项目:+1:

**Comment by CheckChe0803** [comment]
项目还需要用到kafka, 目前推荐系统主要还是基于实时热度,离线训练系统还没有加入

**Comment by vector4wang** [comment]
哈哈哈，我这hbase kafka flink 都一并学了 会用就行，做完刚把hbase过了一遍、、、

能实时推就行， 我们现在已经有离线推荐了，比较传统，定时的去同步日志数据，然后算法的伙伴去拿日志数据计算推荐结果。。。。。


所以现在就差实时的，有demo跑起来，大家看了之后可能会产生很多启发

**Comment by vector4wang** [comment]
老哥，能否加个微信，膜拜啊 我的wx是   BMHJQS  ,

**Comment by vector4wang** [comment]
能否把每个人物的kafka消息体贴一下， 现在就差消息体格式了。。。

**Comment by CheckChe0803** [comment]
消息格式在resource文件夹下有说明

**Comment by vector4wang** [comment]
好的，今天在弄kafka了，争取把整个流程打通

老哥，目测你这个仓库会火！！！

过段时间，我看看能否提个pr对项目做下可配置化的改造。。。

**Comment by vector4wang** [comment]
老哥有微信群、qq群吗，方便拉一下吗

**Comment by CheckChe0803** [comment]
你可以加我微信 DongniVirgo 互相交流下
最近忙着找工作,应该会放缓更新

**Comment by vector4wang** [comment]
恩恩，我尽量自己去调试，昨天弄明白了项目的整个流程，应该会很快走通
