### ISSUE TITLE
请教个问题 关于部署

### ISSUE THREAD

**Issue by zyhnjust** [CheckChe0803/flink-recommandSystem-demo#10]
将上述部署的几个服务的ip和端口号分别配置在flink-2-hbase和web服务中，然后首先在flink-2-hbase中的根目录执行mvn clean install目的是将其打包并放置在本地仓库中，然后再分别启动task目录下的task，直接在idea中右键启动就行了；接着把SchedulerJob启动起来，定时的去结算协同过滤和用户画像所需要的分数;

- 请问， 这个task 是哪个目录， 顶级目录没找到。 
mvn clean install 可以执行么， 为什么有些错误 谢谢

**Comment by vector4wang** [comment]
如图
![image](https://user-images.githubusercontent.com/9328963/63208372-ad6b5300-c105-11e9-80d9-ac0936f612dd.png)

报的什么错误

**Comment by CheckChe0803** [comment]
如果是本地测试的话,建议直接在idea中启动任务即可
task包中的每一个类文件都是一个单独的flink任务,可以根据需求开启

**Comment by zyhnjust** [comment]
了解了， 以为有单独的task 脚本。 谢谢
