### ISSUE TITLE
前台推荐页面 和后台数据展示 是一个网址么 还是有别的

### ISSUE THREAD

**Issue by zyhnjust** [CheckChe0803/flink-recommandSystem-demo#11]
你好， 不好意思没找到别的渠道就开个issue吧。 
部署之后， 页面默认 xxx：8082
然后打开之后没有数据， 左边热榜， 右边是那个日志图。 没有看到可以点的地方。 
请教是几个页面么。 
我看controller 也没有暴露别的， 是不是理解不对。  
![image](https://user-images.githubusercontent.com/9712654/63324191-26fb7f00-c35a-11e9-8d2e-75617d62f660.png)

**Comment by CheckChe0803** [comment]
您好,后台页面第一次启动是没有数据的,因为此时还没有开始有用户的点击行为进入日志
建议可以模拟一些数据放入redis中即可,模拟已经存在的热度数据
如 set 0 123;
set 1 321之类的;
最后一个数字代表产品id(范围0-1000)

**Comment by zyhnjust** [comment]
谢谢您这么快的回复。 
刚才看到代码里getBackStage 是从redis 拿， 然后放到热门里面。 现在对上了。 
1 不过你的图还有一些别的可以收藏什么的， 这里怎么只能看到一个热度， 右边的那些应该在哪里放点数据？ 
2 你web的user。html 是哪里用的， 怎么没有看到 controller的入口。 可能是一个问题
望不吝指教。 

-- 放了redis 目前是
![image](https://user-images.githubusercontent.com/9712654/63329264-2c5dc700-c364-11e9-9ad9-6cd120af9933.png)

**Comment by CheckChe0803** [comment]
不用客气!
在web子目录下的controller下,有两个controller文件,分别对应后台监控和前台推荐,可以查看一下

**Comment by zyhnjust** [comment]
哦是的，我后台推荐协同算法那块可能有的数据不对， 有exception 怪不得看不到页面。 
回头再仔细对一下， thanks。

**Comment by pms666** [comment]
> 哦是的，我后台推荐协同算法那块可能有的数据不对， 有exception 怪不得看不到页面。
> 回头再仔细对一下， thanks。

你好 数据的问题解决了吗，我这也是后台监控能打开页面，前台推荐访问时后台报错。
可以指点一下嘛
