### ISSUE TITLE
关于kafka队列的问题

### ISSUE THREAD

**Issue by liudhzhyym** [CheckChe0803/flink-recommandSystem-demo#13]
你好~ 你的项目非常棒，最近照着你的文档基本搭好了环境~不过在看代码时有个疑问。

flink-2-hbase里面有6个task，分别con、history这两个topic里面取数据，但是在web项目里面，我只看到了在点击收藏、加车等按钮时，有往con这个topic发数据，搜遍整个工程，并没有发现往history这个topic发数据的代码。

```
## UserHistoryTask.java
DataStreamSource<String> dataStream = env.addSource(new FlinkKafkaConsumer<String>("history", new SimpleStringSchema(), properties));
```
请问下history这个topic的数据是从哪里来的？

**Comment by Roy-se7en** [comment]
> 
你好。部署文档能不能重新发一下
