### ISSUE TITLE
部署问题

### ISSUE THREAD

**Issue by yangwenxin847** [CheckChe0803/flink-recommandSystem-demo#19]
![image](https://user-images.githubusercontent.com/44188571/66905813-23723480-f039-11e9-8cce-5d44ee30ecc6.png)
在idea中在执行打包时报错，在Hbaseclient连接zookeeper时，超时，无法连接，已将卡在这1天了，网上各种搜无果，希望master可以帮一下忙

**Comment by CheckChe0803** [comment]
建议检查下是否同时开始hbase自带zk和独立zk,如果同时开启的话可尝试关掉一个先
