### ISSUE TITLE
HBase cannot be accessed

### ISSUE THREAD

**Issue by angelamie001** [CheckChe0803/flink-recommandSystem-demo#24]
According to your steps, HBase cannot be accessed 
https://xinze.fun/2019/11/19/使用Docker部署Flink大数据项目/

**Comment by CheckChe0803** [comment]
The steps to build hbase docker is complicated， this post show what i do to build hbase docker image. If you have a normal hbase environment，it's also can be use for this project
https://xinze.fun/2019/11/20/%E4%BD%BF%E7%94%A8Docker%E6%90%AD%E5%BB%BA%E4%BC%AA%E5%88%86%E5%B8%83%E5%BC%8FHbase-%E5%A4%96%E7%BD%AEZookeeper/

**Comment by angelamie001** [comment]
按照你说的创建伪分布式的hbase镜像就可以访问到hbase了吗？你给出的步骤太简略了，有没有详细一些的？

**Comment by CheckChe0803** [comment]
最简单的办法： 直接拉我的docker image  -> [ docker pull xinze0803/hbase ]

普通的办法： 不使用docker，直接搭建一个普通的hbase环境就可以了

麻烦的办法： 按照我的blog 自己搭建一个本地的hbase image （需要注意的是hbase需要配置成伪分布式 并且 docker 容器配置host ）

**Comment by angelamie001** [comment]
我拉取的你的镜像 根据你的部署说明 docker安装的各个组件 idea启动项目后 连不上hbase

**Comment by angelamie001** [comment]
hbase在win7的虚拟机的docker容器中 idea在mac上

**Comment by CheckChe0803** [comment]
尝试用一个网络环境下试试呢？

**Comment by angelamie001** [comment]
是在一个局域网

**Comment by angelamie001** [comment]
https://www.jianshu.com/p/061246fb42b4 根据这个做的伪分布式 是不是不需要zookeeper

**Comment by CheckChe0803** [comment]
你可以完全不使用docker来搭建hbase。
在对hbase不熟悉的情况下，推荐直接使用普通的方法搭建一个简单的hbase环境即可，网上教程很多

**Comment by angelamie001** [comment]
可以访问了 是虚机没开放端口 我是刚学习大数据 也不知道怎么做 想跟着大佬们做做项目 可不可以加个微信 一起学习

**Comment by CheckChe0803** [comment]
其他issue里面有

**Comment by CheckChe0803** [comment]
其他issue里面有
