### ISSUE TITLE
关于项目docker部署完成后前端页面端口问题

### ISSUE THREAD

**Issue by bobmayuze** [CheckChe0803/flink-recommandSystem-demo#26]
Hi, 非常感谢你写了这个教程。

在阅读你的[博客文章](https://xinze.fun/2019/11/19/%E4%BD%BF%E7%94%A8Docker%E9%83%A8%E7%BD%B2Flink%E5%A4%A7%E6%95%B0%E6%8D%AE%E9%A1%B9%E7%9B%AE/l)中，我没找到 前台推荐页面 和 后台数据大屏 前端的端口号。看了了docker-compose.yml里面似乎也没有对 web 这个folder的操作。是需要单独启动嘛？

**Comment by CheckChe0803** [comment]
Web项目使用SpringBoot搭建，可以自己在IDE中启动或者打包启动
主程序地址在[RecommandApplication.java](https://github.com/CheckChe0803/flink-recommandSystem-demo/blob/master/web/src/main/java/com/demo/RecommandApplication.java)

**Comment by bobmayuze** [comment]
我用IDEA打开Web然后启动项目时报错说Druid 链接失败。但是SQL的container是已经成功启动且有执行migration的脚本的 如下是报错信息：
```
2020-02-05 22:51:23.285 ERROR 98461 --- [           main] com.alibaba.druid.pool.DruidDataSource   : init datasource error, url: jdbc:mysql://localhost:3308/con?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
```

想知道是不是SQL在docker-compose里面没有做端口转发？

**Comment by bobmayuze** [comment]
已经解决，解决方法是
1. 在[docker-compose.yml](https://github.com/CheckChe0803/flink-recommandSystem-demo/blob/master/resources/docker/docker-compose/docker-compose.yml) 文件中对mysql 添加了
```
    ports:
      - "3306:3306"      
      - "33060:33060"
```

2. 修改 [application.yml](https://github.com/CheckChe0803/flink-recommandSystem-demo/blob/master/web/src/main/resources/application.yml) Druid链接端口 和 [config.properties](https://github.com/CheckChe0803/flink-recommandSystem-demo/blob/master/flink-2-hbase/src/main/resources/config.properties) 从3308 至3306
