### ISSUE TITLE
shell脚本的topic是否设置错误

### ISSUE THREAD

**Issue by waterzmh** [CheckChe0803/flink-recommandSystem-demo#32]
6个定时任务都是针对“con”主题进行消费，找遍了工程所有地方也没有找到生产"con"主题消息的地方，唯一的初始化kafka数据的地方就是generator.sh，发现你写的生产msg到"log"主题，请问是否是书写错误，正确的主题应该是"con"

**Comment by LeeMoonCh** [comment]
并不是定时任务，而是flink任务对接的kafka的topic都是con，如果但看LogMapFunction逻辑，那么他的逻辑应该是从topic的con中获取日志数据，然后存到hbase的con中，并且看日志形式应该是没有问题的正好和脚本中生产的数据是一至的，所以这里订阅的con应该就是脚本中的`log`主题，没错了。
